name: Release

on:
  release:
    types: [released]
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Bump primary formula
        uses: mislav/bump-homebrew-formula-action@b3327118b2153c82da63fd9cbf58942146ee99f0 # v3.1
        if: "contains(github.ref, 'v4')"
        with:
          formula-name: hometown-prompt
          formula-path: hometown-prompt.rb
          homebrew-tap: olets/homebrew-tap
          download-url: https://github.com/olets/hometown-prompt.git
          commit-message: |
            feat({{formulaName}}): publish {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

      - name: Bump v4.x formula
        uses: mislav/bump-homebrew-formula-action@b3327118b2153c82da63fd9cbf58942146ee99f0 # v3.1
        if: "contains(github.ref, 'v4')"
        with:
          formula-name: hometown-prompt@4
          formula-path: hometown-prompt@4.rb
          homebrew-tap: olets/homebrew-tap
          commit-message: |
            feat({{formulaName}}): publish {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

      - name: Bump v3.x formula
        uses: mislav/bump-homebrew-formula-action@b3327118b2153c82da63fd9cbf58942146ee99f0 # v3.1
        if: "contains(github.ref, 'v3')"
        with:
          formula-name: hometown-prompt@3
          formula-path: hometown-prompt@3.rb
          homebrew-tap: olets/homebrew-tap
          download-url: https://github.com/olets/hometown-prompt.git
          commit-message: |
            feat({{formulaName}}): publish {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
